"""empty message

Revision ID: af317ce5e03f
Revises: 
Create Date: 2021-02-10 15:57:20.833883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af317ce5e03f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('airline', sa.String(length=6), nullable=True),
    sa.Column('flight_no', sa.String(length=8), nullable=True),
    sa.Column('dep', sa.String(length=10), nullable=True),
    sa.Column('dest', sa.String(length=10), nullable=True),
    sa.Column('acft_reg', sa.String(length=8), nullable=True),
    sa.Column('status', sa.String(length=14), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('planets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('name', sa.String(length=75), nullable=True),
    sa.Column('surname', sa.String(length=75), nullable=True),
    sa.Column('password', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('planets')
    op.drop_table('flights')
    # ### end Alembic commands ###
